version: '2'
services:
  chorserv-server-site-bundle:
    image: chr-serv
    restart: always
    volumes_from:
      - chr-data
  chr-cms:
    image: chr-cms
    restart: always
    volumes_from:
      - chr-data
    depends_on:
      - chr-data
      - chorserv-server-site-bundle
  chr-data:
    image: chr-data:latest
    volumes:
      - /data
      - /Servertools
      - /bilderStrukturen
    command: /bin/true
  chr-entry:
    image: chr-entry
    restart: always
    expose:
      - "80"
      - "443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - chr-data
      - chorserv-server-site-bundle
      - chr-cms
    
    
